+ source /root/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Fri Jan  6 14:45:53 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL libreswan
+ pkgs=libreswan
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs libreswan --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpb74oud18
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpb74oud18
+ systemctl start firewalld
Failed to start firewalld.service: Unit firewalld.service not found.
+ DNF_INSTALL libreswan 2
+ pkgs=libreswan
+ node=2
+ '[' -z /tmp/tmpb74oud18 ']'
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs libreswan --node 2 --tempfile /tmp/tmpb74oud18
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 176, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z /tmp/tmpb74oud18 ']'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Jan  6 14:46:41 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Fri Jan  6 14:46:42 2023 - INFO  - Start executing testcase.
+ systemctl enable ipsec --now
Created symlink /etc/systemd/system/multi-user.target.wants/ipsec.service â†’ /usr/lib/systemd/system/ipsec.service.
Job for ipsec.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 33'
+ message='oe_test_host_to_host_vpn.sh line 33'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 33'
Fri Jan  6 14:46:54 2023 - ERROR - oe_test_host_to_host_vpn.sh line 33
+ return 0
+ ipsec initnss
Initializing NSS database

+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep success
+ firewall-cmd --add-service=ipsec
oe_test_host_to_host_vpn.sh: line 36: firewall-cmd: command not found
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 37'
+ message='oe_test_host_to_host_vpn.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 37'
Fri Jan  6 14:46:56 2023 - ERROR - oe_test_host_to_host_vpn.sh line 37
+ return 0
+ firewall-cmd --runtime-to-permanent
oe_test_host_to_host_vpn.sh: line 38: firewall-cmd: command not found
+ grep success
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 39'
+ message='oe_test_host_to_host_vpn.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 39'
Fri Jan  6 14:46:57 2023 - ERROR - oe_test_host_to_host_vpn.sh line 39
+ return 0
++ ipsec newhostkey --nssdir /etc/ipsec.d/
++ awk '/Generated/{print $7}'
+ left_ckaid=8ec79d840cc4ccfe5da674cbfeb17b22c501ca3b
++ ipsec showhostkey --left --ckaid 8ec79d840cc4ccfe5da674cbfeb17b22c501ca3b --nssdir /etc/ipsec.d/
++ grep leftrsasigkey
++ sed 's/^[ \t]*//g'
++ awk -F leftrsasigkey= '{print $2}'
+ left_rsa=0sAwEAAbL7/JiiBs9K7hjSBcjkDtXoThxuBrtdDQW1GJKj6igGpPM8/SqZL51z2uKTN6UlaksSbBfbbJsnarj/9R/yRy1YdJ9oTqh21G/5v8J+Dz1SBFkrbOep/T6aosdxerP2AjwmBZUwV7zhIActvmsXLdGjcsyAH4t/AF8S939ViSt4+LQ8OayZyrELl8D+kHdYeuh2u49EbCYWpQElV5+KK4olu0KH5jXGS5yI4VGwPf8xqa1dBlKq3FSSks+SFj9Ug45hQFEktVhFuhJJmEA8dFlH6vMJqYEFN/vtO/zHLNauNBFJzkYO420ZAdtpG+rR7s2o/9Rxc/L5wpDasIcWFo9+582TIcdVgNjtvrDVEtjXb4gfvjYoU48sgI5R2CZcz/XDhLuCQTT7IpXyX32NK/s1sGd76vuW0EwaCtqB0fLKPyUIdumoG1MnzK9AEdyoZZoUpUG20XtCEJnTrRD8thQUwshbbNZ2KrZOC1OGaqkSWZIu3pkAvID0anrE15eCgfVJ2HQWra+CPj/HhJEMW1SOxkCnOw25g+ZDuAhPQB/vGOv8s7/hDuCVeFt+K0E=
+ P_SSH_CMD --cmd 'systemctl start firewalld;systemctl enable ipsec --now' --node 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'systemctl start firewalld;systemctl enable ipsec --now' --node 2
Fri Jan  6 14:47:06 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 44'
+ message='oe_test_host_to_host_vpn.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 44'
Fri Jan  6 14:47:07 2023 - ERROR - oe_test_host_to_host_vpn.sh line 44
+ return 0
+ P_SSH_CMD --cmd 'firewall-cmd --add-service=\"ipsec\";firewall-cmd --runtime-to-permanent' --node 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'firewall-cmd --add-service=\"ipsec\";firewall-cmd --runtime-to-permanent' --node 2
Fri Jan  6 14:47:10 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 46'
+ message='oe_test_host_to_host_vpn.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 46'
Fri Jan  6 14:47:11 2023 - ERROR - oe_test_host_to_host_vpn.sh line 46
+ return 0
+ P_SSH_CMD --cmd 'ipsec newhostkey --nssdir /etc/ipsec.d/ 2>&1 | grep Generated | cut -d '\'' '\'' -f 7 >/tmp/key.txt' --node 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'ipsec newhostkey --nssdir /etc/ipsec.d/ 2>&1 | grep Generated | cut -d '\'' '\'' -f 7 >/tmp/key.txt' --node 2
Fri Jan  6 14:47:13 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 48'
+ message='oe_test_host_to_host_vpn.sh line 48'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 48'
Fri Jan  6 14:47:14 2023 - ERROR - oe_test_host_to_host_vpn.sh line 48
+ return 0
+ SSH_SCP @:/tmp/key.txt /tmp
+ src=@:/tmp/key.txt
+ dest=/tmp
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/key.txt -d /tmp
Fri Jan  6 14:47:15 2023 - WARN  - the remote password uses the default configuration.
Fri Jan  6 14:47:16 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/key.txt /tmp
ssh: Could not resolve hostname : Name or service not known

+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 1'
+ message='Failed in remote SCP operation: 1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 1'
Fri Jan  6 14:47:17 2023 - ERROR - Failed in remote SCP operation: 1
+ return 1
++ cat /tmp/key.txt
cat: /tmp/key.txt: No such file or directory
+ right_ckaid=
+ P_SSH_CMD --cmd 'ipsec showhostkey --right --ckaid  --nssdir /etc/ipsec.d/ | grep rightrsasigkey > /tmp/rsa.txt' --node 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'ipsec showhostkey --right --ckaid  --nssdir /etc/ipsec.d/ | grep rightrsasigkey > /tmp/rsa.txt' --node 2
Fri Jan  6 14:47:20 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 53'
+ message='oe_test_host_to_host_vpn.sh line 53'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 53'
Fri Jan  6 14:47:20 2023 - ERROR - oe_test_host_to_host_vpn.sh line 53
+ return 0
+ SSH_SCP @:/tmp/rsa.txt /tmp
+ src=@:/tmp/rsa.txt
+ dest=/tmp
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/rsa.txt -d /tmp
Fri Jan  6 14:47:22 2023 - WARN  - the remote password uses the default configuration.
Fri Jan  6 14:47:22 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/rsa.txt /tmp
ssh: Could not resolve hostname : Name or service not known

+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 1'
+ message='Failed in remote SCP operation: 1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 1'
Fri Jan  6 14:47:24 2023 - ERROR - Failed in remote SCP operation: 1
+ return 1
++ cat /tmp/rsa.txt
++ sed 's/^[ \t]*//g'
++ awk -F rightrsasigkey= '{print $2}'
cat: /tmp/rsa.txt: No such file or directory
+ right_rsa=
+ echo -e 'conn mytunnel\n    leftid=@west\n    left=127.0.0.1\n    leftrsasigkey=0sAwEAAbL7/JiiBs9K7hjSBcjkDtXoThxuBrtdDQW1GJKj6igGpPM8/SqZL51z2uKTN6UlaksSbBfbbJsnarj/9R/yRy1YdJ9oTqh21G/5v8J+Dz1SBFkrbOep/T6aosdxerP2AjwmBZUwV7zhIActvmsXLdGjcsyAH4t/AF8S939ViSt4+LQ8OayZyrELl8D+kHdYeuh2u49EbCYWpQElV5+KK4olu0KH5jXGS5yI4VGwPf8xqa1dBlKq3FSSks+SFj9Ug45hQFEktVhFuhJJmEA8dFlH6vMJqYEFN/vtO/zHLNauNBFJzkYO420ZAdtpG+rR7s2o/9Rxc/L5wpDasIcWFo9+582TIcdVgNjtvrDVEtjXb4gfvjYoU48sgI5R2CZcz/XDhLuCQTT7IpXyX32NK/s1sGd76vuW0EwaCtqB0fLKPyUIdumoG1MnzK9AEdyoZZoUpUG20XtCEJnTrRD8thQUwshbbNZ2KrZOC1OGaqkSWZIu3pkAvID0anrE15eCgfVJ2HQWra+CPj/HhJEMW1SOxkCnOw25g+ZDuAhPQB/vGOv8s7/hDuCVeFt+K0E=\n    
    rightid=@east\n    right=\n    rightrsasigkey=\n    
    authby=rsasig\n    auto=start'
+ SSH_SCP /etc/ipsec.d/my_host-to-host.conf @:/etc/ipsec.d/
+ src=/etc/ipsec.d/my_host-to-host.conf
+ dest=@:/etc/ipsec.d/
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen-riscv/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s /etc/ipsec.d/my_host-to-host.conf -d @:/etc/ipsec.d/
Fri Jan  6 14:47:25 2023 - WARN  - the remote password uses the default configuration.
Fri Jan  6 14:47:25 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r /etc/ipsec.d/my_host-to-host.conf @:/etc/ipsec.d/
ssh: Could not resolve hostname : Name or service not known

lost connection
+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 1'
+ message='Failed in remote SCP operation: 1'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 1'
Fri Jan  6 14:47:26 2023 - ERROR - Failed in remote SCP operation: 1
+ return 1
+ ipsec auto --add mytunnel
Failed to load connection right= is not set
+ CHECK_RESULT 255
+ actual_result=255
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 255 ']'
+ '[' 0 -eq 0 ']'
+ test 255x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 63'
+ message='oe_test_host_to_host_vpn.sh line 63'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 63'
Fri Jan  6 14:47:28 2023 - ERROR - oe_test_host_to_host_vpn.sh line 63
+ return 0
+ systemctl restart ipsec
Job for ipsec.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
+ ipsec setup start
Redirecting to: systemctl start ipsec.service
Job for ipsec.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
+ P_SSH_CMD --cmd 'ipsec auto --add mytunnel;systemctl restart ipsec;ipsec setup start' --node 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'ipsec auto --add mytunnel;systemctl restart ipsec;ipsec setup start' --node 2
Fri Jan  6 14:47:47 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ ipsec auto --up mytunnel
whack: is Pluto running?  connect() for "/run/pluto/pluto.ctl" failed (111 Connection refused)
+ CHECK_RESULT 33
+ actual_result=33
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 33 ']'
+ '[' 0 -eq 0 ']'
+ test 33x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 69'
+ message='oe_test_host_to_host_vpn.sh line 69'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 69'
Fri Jan  6 14:47:48 2023 - ERROR - oe_test_host_to_host_vpn.sh line 69
+ return 0
+ P_SSH_CMD --cmd 'ipsec auto --up mytunnel' --node 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py --cmd 'ipsec auto --up mytunnel' --node 2
Fri Jan  6 14:47:51 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_host_to_host_vpn.sh line 71'
+ message='oe_test_host_to_host_vpn.sh line 71'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_host_to_host_vpn.sh line 71'
Fri Jan  6 14:47:52 2023 - ERROR - oe_test_host_to_host_vpn.sh line 71
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Fri Jan  6 14:47:52 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Jan  6 14:47:53 2023 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Jan  6 14:47:54 2023 - INFO  - start environment cleanup.
+ systemctl stop ipsec
+ firewall-cmd --remove-service=ipsec
oe_test_host_to_host_vpn.sh: line 79: firewall-cmd: command not found
+ firewall-cmd --runtime-to-permanent
oe_test_host_to_host_vpn.sh: line 80: firewall-cmd: command not found
+ P_SSH_CMD 'systemctl stop ipsec;firewall-cmd --remove-service=ipsec;firewall-cmd --runtime-to-permanent' 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py 'systemctl stop ipsec;firewall-cmd --remove-service=ipsec;firewall-cmd --runtime-to-permanent' 2
usage: ssh_cmd.py [-h] --cmd CMD [--node NODE] [--ip IP] [--password PASSWORD]
                  [--port PORT] [--user USER] [--timeout TIMEOUT]
ssh_cmd.py: error: the following arguments are required: --cmd
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpb74oud18 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpb74oud18
+ '[' 0 -ne 0 ']'
+ DNF_REMOVE 2 libreswan
+ node=2
+ pkg_list=libreswan
+ mode=0
+ [[ -z /tmp/tmpb74oud18 ]]
+ '[' 0 -ne 0 ']'
+ '[' 2 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 2 --pkgs libreswan --tempfile /tmp/tmpb74oud18
Traceback (most recent call last):
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 181, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen-riscv/libs/locallibs/rpm_manage.py", line 142, in rpm_remove
    conn = ssh_cmd.pssh_conn(
  File "/root/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.9/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
+ '[' 0 -ne 0 ']'
+ rm -rf /tmp/key.txt /tmp/rsa.txt /etc/ipsec.d/cert9.db /etc/ipsec.d/key4.db /etc/ipsec.d/my_host-to-host.conf /etc/ipsec.d/pkcs11.txt /var/lib/ipsec/nss/cert9.db /var/lib/ipsec/nss/key4.db
+ P_SSH_CMD 'rm -rf /tmp/key.txt /tmp/rsa.txt /etc/ipsec.d/* /var/lib/ipsec/nss/*.db' 2
+ python3 /root/mugen-riscv/libs/locallibs/ssh_cmd.py 'rm -rf /tmp/key.txt /tmp/rsa.txt /etc/ipsec.d/* /var/lib/ipsec/nss/*.db' 2
usage: ssh_cmd.py [-h] --cmd CMD [--node NODE] [--ip IP] [--password PASSWORD]
                  [--port PORT] [--user USER] [--timeout TIMEOUT]
ssh_cmd.py: error: the following arguments are required: --cmd
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Jan  6 14:48:27 2023 - INFO  - Finish environment cleanup!
