+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Dec 29 00:24:13 2022 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'lxcfs lxcfs-tools'
+ pkgs='lxcfs lxcfs-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs 'lxcfs lxcfs-tools' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpod9f5n31
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpod9f5n31
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Dec 29 00:25:28 2022 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Dec 29 00:25:29 2022 - INFO  - Start testing...
+ test_execution lxcfs.service
+ service=lxcfs.service
++ date '+%Y-%m-%d %T'
+ log_time='2022-12-29 00:25:29'
+ test_restart lxcfs.service
+ service=lxcfs.service
+ systemctl restart lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ CHECK_RESULT 1 0 0 'lxcfs.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service restart failed'
+ LOG_ERROR 'lxcfs.service restart failed'
+ message='lxcfs.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service restart failed'
Thu Dec 29 00:25:46 2022 - ERROR - lxcfs.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Thu Dec 29 00:25:47 2022 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'lxcfs.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service restart failed'
+ LOG_ERROR 'lxcfs.service restart failed'
+ message='lxcfs.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service restart failed'
Thu Dec 29 00:25:53 2022 - ERROR - lxcfs.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Thu Dec 29 00:25:54 2022 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop lxcfs.service
+ CHECK_RESULT 0 0 0 'lxcfs.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'lxcfs.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service stop failed'
+ LOG_ERROR 'lxcfs.service stop failed'
+ message='lxcfs.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service stop failed'
Thu Dec 29 00:26:01 2022 - ERROR - lxcfs.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Thu Dec 29 00:26:01 2022 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ CHECK_RESULT 1 0 0 'lxcfs.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service start failed'
+ LOG_ERROR 'lxcfs.service start failed'
+ message='lxcfs.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service start failed'
Thu Dec 29 00:26:18 2022 - ERROR - lxcfs.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Thu Dec 29 00:26:19 2022 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status lxcfs.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'lxcfs.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service start failed'
+ LOG_ERROR 'lxcfs.service start failed'
+ message='lxcfs.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service start failed'
Thu Dec 29 00:26:25 2022 - ERROR - lxcfs.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Thu Dec 29 00:26:26 2022 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled lxcfs.service
+ service=lxcfs.service
++ systemctl is-enabled lxcfs.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable lxcfs.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/lxcfs.service
+ find /etc/systemd/system/multi-user.target.wants/lxcfs.service
/etc/systemd/system/multi-user.target.wants/lxcfs.service
+ CHECK_RESULT 0 0 0 'lxcfs.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable lxcfs.service
Removed /etc/systemd/system/multi-user.target.wants/lxcfs.service.
+ find /etc/systemd/system/multi-user.target.wants/lxcfs.service
find: ‘/etc/systemd/system/multi-user.target.wants/lxcfs.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'lxcfs.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='lxcfs.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2022-12-29 00:25:29' -u lxcfs.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Dec 29 00:25:30 openEuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 00:25:45 openEuler-riscv64 lxcfs-tools[2251]: time="2022-12-29T00:25:45+08:00" level=error msg="lxcfs is not ready"
Dec 29 00:25:45 openEuler-riscv64 lxcfs-tools[2251]: time="2022-12-29T00:25:45+08:00" level=error msg="lxcfs is not ready"
Dec 29 00:25:45 openEuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
Dec 29 00:25:45 openEuler-riscv64 systemd[1]: Failed to start FUSE filesystem for LXC.
Dec 29 00:25:48 openEuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 00:25:54 openEuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
Dec 29 00:26:02 openEuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 00:26:17 openEuler-riscv64 lxcfs-tools[3490]: time="2022-12-29T00:26:17+08:00" level=error msg="lxcfs is not ready"
Dec 29 00:26:17 openEuler-riscv64 lxcfs-tools[3490]: time="2022-12-29T00:26:17+08:00" level=error msg="lxcfs is not ready"
Dec 29 00:26:17 openEuler-riscv64 systemd[1]: lxcfs.service: Failed with result 'exit-code'.
Dec 29 00:26:17 openEuler-riscv64 systemd[1]: Failed to start FUSE filesystem for LXC.
Dec 29 00:26:20 openEuler-riscv64 systemd[1]: lxcfs.service: Main process exited, code=exited, status=1/FAILURE
+ CHECK_RESULT 0 0 1 'There is an error message for the log of lxcfs.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of lxcfs.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of lxcfs.service'
+ LOG_ERROR 'There is an error message for the log of lxcfs.service'
+ message='There is an error message for the log of lxcfs.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of lxcfs.service'
Thu Dec 29 00:26:35 2022 - ERROR - There is an error message for the log of lxcfs.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Thu Dec 29 00:26:36 2022 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ systemctl start lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ sed -i 's\ExecStart=/usr/bin/lxcfs\ExecStart=/usr/bin/lxcfs -d\g' /usr/lib/systemd/system/lxcfs.service
+ systemctl daemon-reload
+ systemctl reload lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ CHECK_RESULT 1 0 0 'lxcfs.service reload failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service reload failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service reload failed'
+ LOG_ERROR 'lxcfs.service reload failed'
+ message='lxcfs.service reload failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service reload failed'
Thu Dec 29 00:26:57 2022 - ERROR - lxcfs.service reload failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_lxcfs.sh line 35'
+ message='oe_test_service_lxcfs.sh line 35'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_lxcfs.sh line 35'
Thu Dec 29 00:26:58 2022 - ERROR - oe_test_service_lxcfs.sh line 35
+ return 0
+ systemctl status lxcfs.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'lxcfs.service reload causes the service status to change'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='lxcfs.service reload causes the service status to change'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'lxcfs.service reload causes the service status to change'
+ LOG_ERROR 'lxcfs.service reload causes the service status to change'
+ message='lxcfs.service reload causes the service status to change'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'lxcfs.service reload causes the service status to change'
Thu Dec 29 00:26:59 2022 - ERROR - lxcfs.service reload causes the service status to change
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_service_lxcfs.sh line 37'
+ message='oe_test_service_lxcfs.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_service_lxcfs.sh line 37'
Thu Dec 29 00:27:00 2022 - ERROR - oe_test_service_lxcfs.sh line 37
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Dec 29 00:27:00 2022 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 29 00:27:01 2022 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Dec 29 00:27:02 2022 - INFO  - start environment cleanup.
+ sed -i 'sExecStart=/usr/bin/lxcfs -d\ExecStart=/usr/bin/lxcfs\g' /usr/lib/systemd/system/lxcfs.service
sed: -e expression #1, char 55: unterminated `s' command
+ systemctl daemon-reload
+ systemctl reload lxcfs.service
Job for lxcfs.service failed because the control process exited with error code.
See "systemctl status lxcfs.service" and "journalctl -xeu lxcfs.service" for details.
+ systemctl stop lxcfs.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpod9f5n31 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpod9f5n31
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Dec 29 00:27:36 2022 - INFO  - Finish environment cleanup!
