+ source ../common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Tue Feb 14 01:11:05 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL atune
+ pkgs=atune
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs atune --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpydp2vbp5
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpydp2vbp5
++ lsblk
++ awk 'NR==1{print $1}'
++ grep disk
+ disk_name=vda
+ sed -i 's\disk = sda\disk = vda\g' /etc/atuned/atuned.cnf
+ sed -i 's\network = enp189s0f0\network = \g' /etc/atuned/atuned.cnf
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Feb 14 01:20:47 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Tue Feb 14 01:20:50 2023 - INFO  - Start testing...
+ test_execution atuned.service
+ service=atuned.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-02-14 01:20:50'
+ test_restart atuned.service
+ service=atuned.service
+ systemctl restart atuned.service
Job for atuned.service failed because the control process exited with error code.
See "systemctl status atuned.service" and "journalctl -xeu atuned.service" for details.
+ CHECK_RESULT 1 0 0 'atuned.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned.service restart failed'
+ LOG_ERROR 'atuned.service restart failed'
+ message='atuned.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'atuned.service restart failed'
Tue Feb 14 01:21:34 2023 - ERROR - atuned.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 34'
+ message='../common/common_lib.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 34'
Tue Feb 14 01:21:36 2023 - ERROR - ../common/common_lib.sh line 34
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status atuned.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'atuned.service restart failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned.service restart failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned.service restart failed'
+ LOG_ERROR 'atuned.service restart failed'
+ message='atuned.service restart failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'atuned.service restart failed'
Tue Feb 14 01:21:45 2023 - ERROR - atuned.service restart failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 37'
+ message='../common/common_lib.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 37'
Tue Feb 14 01:21:47 2023 - ERROR - ../common/common_lib.sh line 37
+ return 0
+ systemctl stop atuned.service
+ CHECK_RESULT 0 0 0 'atuned.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atuned.service stop failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Active: inactive'
+ systemctl status atuned.service
+ CHECK_RESULT 1 0 0 'atuned.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned.service stop failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned.service stop failed'
+ LOG_ERROR 'atuned.service stop failed'
+ message='atuned.service stop failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'atuned.service stop failed'
Tue Feb 14 01:21:56 2023 - ERROR - atuned.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Tue Feb 14 01:21:58 2023 - ERROR - ../common/common_lib.sh line 42
+ return 0
+ systemctl start atuned.service
Job for atuned.service failed because the control process exited with error code.
See "systemctl status atuned.service" and "journalctl -xeu atuned.service" for details.
+ CHECK_RESULT 1 0 0 'atuned.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned.service start failed'
+ LOG_ERROR 'atuned.service start failed'
+ message='atuned.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'atuned.service start failed'
Tue Feb 14 01:22:02 2023 - ERROR - atuned.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 44'
+ message='../common/common_lib.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 44'
Tue Feb 14 01:22:04 2023 - ERROR - ../common/common_lib.sh line 44
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status atuned.service
+ grep 'Active: active'
+ CHECK_RESULT 1 0 0 'atuned.service start failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='atuned.service start failed'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'atuned.service start failed'
+ LOG_ERROR 'atuned.service start failed'
+ message='atuned.service start failed'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'atuned.service start failed'
Tue Feb 14 01:22:13 2023 - ERROR - atuned.service start failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 47'
+ message='../common/common_lib.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 47'
Tue Feb 14 01:22:14 2023 - ERROR - ../common/common_lib.sh line 47
+ return 0
+ test_enabled atuned.service
+ service=atuned.service
++ systemctl is-enabled atuned.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ grep 'Created symlink'
++ systemctl enable atuned.service
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/atuned.service
+ find /etc/systemd/system/multi-user.target.wants/atuned.service
/etc/systemd/system/multi-user.target.wants/atuned.service
+ CHECK_RESULT 0 0 0 'atuned.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='atuned.service enable failed'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable atuned.service
Removed /etc/systemd/system/multi-user.target.wants/atuned.service.
+ find /etc/systemd/system/multi-user.target.wants/atuned.service
find: ‘/etc/systemd/system/multi-user.target.wants/atuned.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'atuned.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='atuned.service disable failed'
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-02-14 01:20:50' -u atuned.service
+ grep -v -i 'DEBUG\|INFO\|WARNING'
+ grep -i 'fail\|error'
Feb 14 01:21:32 openEuler-riscv64 atuned[2219]: fatal error: runtime: no plugin module data
Feb 14 01:21:32 openEuler-riscv64 systemd[1]: atuned.service: Failed with result 'exit-code'.
Feb 14 01:21:32 openEuler-riscv64 systemd[1]: Failed to start A-Tune Daemon.
Feb 14 01:22:00 openEuler-riscv64 atuned[3617]: fatal error: runtime: no plugin module data
Feb 14 01:22:00 openEuler-riscv64 systemd[1]: atuned.service: Failed with result 'exit-code'.
Feb 14 01:22:00 openEuler-riscv64 systemd[1]: Failed to start A-Tune Daemon.
+ CHECK_RESULT 0 0 1 'There is an error message for the log of atuned.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of atuned.service'
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of atuned.service'
+ LOG_ERROR 'There is an error message for the log of atuned.service'
+ message='There is an error message for the log of atuned.service'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of atuned.service'
Tue Feb 14 01:22:45 2023 - ERROR - There is an error message for the log of atuned.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Tue Feb 14 01:22:48 2023 - ERROR - ../common/common_lib.sh line 28
+ return 0
+ test_reload atuned.service
+ service=atuned.service
+ systemctl start atuned.service
Job for atuned.service failed because the control process exited with error code.
See "systemctl status atuned.service" and "journalctl -xeu atuned.service" for details.
+ grep 'Job type reload is not applicable'
+ systemctl reload atuned.service
Failed to reload atuned.service: Job type reload is not applicable for unit atuned.service.
+ CHECK_RESULT 0 0 0 'Job type reload is not applicable for unit atuned.service'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Job type reload is not applicable for unit atuned.service'
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep 'Active: active'
+ systemctl status atuned.service
+ systemctl status atuned.service
+ grep 'inactive (dead)'
+ return 1
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Tue Feb 14 01:22:54 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 6
+ test 6 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Feb 14 01:22:56 2023 - ERROR - failed to execute the case.
+ exit 6
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Tue Feb 14 01:22:58 2023 - INFO  - start environment cleanup.
+ systemctl stop atuned.service
+ sed -i 's\disk = vda\disk = sda\g' /etc/atuned/atuned.cnf
+ sed -i 's\network = \network = enp189s0f0\g' /etc/atuned/atuned.cnf
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpydp2vbp5 ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpydp2vbp5
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Tue Feb 14 01:24:26 2023 - INFO  - Finish environment cleanup!
